export enum AuthMutationTypes {
  SET_IS_LOGGED_IN = 'SET_IS_LOGGED_IN',
  SET_USER = 'SET_USER',
  SET_SIGN_UP_ERROR = 'SET_SIGN_UP_ERROR',
  SET_LOGGED_IN_ERROR = 'SET_LOGGED_IN_ERROR',
  RESET_USER = 'RESET_USER',
  SET_IS_LOADING = 'SET_IS_LOADING',
  SET_IS_LOADED = 'SET_IS_LOADED',
  SET_SIGN_UP_FULLFILLED = 'SET_SIGN_UP_FULLFILLED'
}
