export enum WorkspaceMutationTypes {
  SET_WORKSPACES = 'WORKSPACE/SET_WORKSPACES',
  SET_SHARED_WORKSPACES = 'WORKSPACE/SET_SHARED_WORKSPACES',
  SET_OWNERS_WORKSPACES_LOADING = 'WORKSPACE/SET_OWNERS_WORKSPACES_LOADING',
  SET_OWNERS_WORKSPACES_LOADED = 'WORKSPACE/SET_OWNERS_WORKSPACES_LOADED',
  SET_SHARED_WORKSPACES_LOADING = 'WORKSPACE/SET_SHARED_WORKSPACES_LOADING',
  SET_SHARED_WORKSPACES_LOADED = 'WORKSPACE/SET_SHARED_WORKSPACES_LOADED',
  SET_WORKSPACE_SHARE_CODE = 'WORKSPACE/SET_WORKSPACE_SHARE_CODE',
  SET_USER_WORKSPACE_REQUESTS = 'WORKSPACE/SET_USER_WORKSPACE_REQUESTS',
  REMOVE_WORKSPACE_REQUEST = 'WORKSPACE/REMOVE_WORKSPACE_REQUEST',
  SET_WORKSPACE_CARDS = 'WORKSPACE/SET_WORKSPACE_CARDS',
}
