export enum WorkspaceMutationTypes {
  SET_WORKSPACES = 'WORKSPACE/SET_WORKSPACES',
  SET_WORKSPACES_LOADING = 'WORKSPACE/SET_WORKSPACES_LOADING',
  SET_WORKSPACES_LOADED = 'WORKSPACE/SET_WORKSPACES_LOADED'
}
