export enum CoworkerActionTypes {
  GET_USER_CONNECTIONS = 'GET_USER_CONNECTIONS',
  GET_USERS = 'GET_USERS',
  SEND_CONNECTION_REQUEST = 'SEND_CONNECTION_REQUEST',
  GET_REQUESTED_CONNECTION_REQUESTS = 'GET_REQUESTED_CONNECTION_REQUESTS',
  GET_RECEIVED_CONNECTION_REQUESTS = 'GET_RECEIVED_CONNECTION_REQUESTS',
  DELETE_CONNECTION = 'DELETE_CONNECTION',
  DECLINE_CONNECTION_REQUEST = 'DECLINE_CONNECTION_REQUEST',
  ACCEPT_CONNECTION_REQUEST = 'ACCEPT_CONNECTION_REQUEST',
}
