export enum CoworkerActionTypes {
  GET_USER_CONNECTIONS = 'CoworkerActionTypes/GET_USER_CONNECTIONS',
  GET_USERS = 'CoworkerActionTypes/GET_USERS',
  SEND_CONNECTION_REQUEST = 'CoworkerActionTypes/SEND_CONNECTION_REQUEST',
  GET_REQUESTED_CONNECTION_REQUESTS = 'CoworkerActionTypes/GET_REQUESTED_CONNECTION_REQUESTS',
  GET_RECEIVED_CONNECTION_REQUESTS = 'CoworkerActionTypes/GET_RECEIVED_CONNECTION_REQUESTS',
  DELETE_CONNECTION = 'CoworkerActionTypes/DELETE_CONNECTION',
  DECLINE_CONNECTION_REQUEST = 'CoworkerActionTypes/DECLINE_CONNECTION_REQUEST',
  ACCEPT_CONNECTION_REQUEST = 'CoworkerActionTypes/ACCEPT_CONNECTION_REQUEST',
  GET_USER_BY_ID = 'CoworkerActionTypes/GET_USER_BY_ID',
}
