export enum CoworkerMutationTypes {
  SET_USER_CONNECTIONS = 'COWORKER/SET_USER_CONNECTIONS',
  SET_USERS = 'COWORKER/SET_USERS',
  SET_IS_LOADING = 'COWORKER/SET_IS_LOADING',
  SET_IS_LOADED = 'COWORKER/SET_IS_LOADED'
}
