export enum CoworkerMutationTypes {
  SET_USER_CONNECTIONS = 'COWORKER/SET_USER_CONNECTIONS',
  UPDATE_USER_CONNECTIONS = 'COWORKER/UPDATE_USER_CONNECTIONS',
  SET_USERS = 'COWORKER/SET_USERS',
  UPDATE_USERS = 'COWORKER/UPDATE_USERS',
  SET_IS_LOADING = 'COWORKER/SET_IS_LOADING',
  SET_IS_LOADED = 'COWORKER/SET_IS_LOADED',
  SET_REQUESTED_CONNECTION_REQUESTS = 'COWORKER/SET_REQUESTED_CONNECTION_REQUESTS',
  UPDATE_REQUESTED_CONNECTION_REQUESTS = 'COWORKER/UPDATE_REQUESTED_CONNECTION_REQUESTS',
  SET_RECEIVED_CONNECTION_REQUESTS = 'COWORKER/SET_RECEIVED_CONNECTION_REQUESTS',
  UPDATE_RECEIVED_CONNECTION_REQUESTS = 'COWORKER/UPDATE_RECEIVED_CONNECTION_REQUESTS',
  SET_REQUESTS_IS_LOADING = 'COWORKER/SET_REQUESTS_IS_LOADING',
  SET_REQUESTS_IS_LOADED = 'COWORKER/SET_REQUESTS_IS_LOADED'
}
